# Generated TCL script for HIDA Layout Partitioning
# Number of partitions: 4

# Partition 0 functions:
set_directive_allocation -limit 1 -type function forward_node156 -partition 0
set_directive_allocation -limit 1 -type function forward_node161 -partition 0
set_directive_allocation -limit 1 -type function forward -partition 0

# Partition 1 functions:
set_directive_allocation -limit 1 -type function forward_node80 -partition 1
set_directive_allocation -limit 1 -type function forward_node81 -partition 1
set_directive_allocation -limit 1 -type function forward_node82 -partition 1
set_directive_allocation -limit 1 -type function forward_node83 -partition 1
set_directive_allocation -limit 1 -type function forward_node84 -partition 1
set_directive_allocation -limit 1 -type function forward_node85 -partition 1
set_directive_allocation -limit 1 -type function forward_node86 -partition 1
set_directive_allocation -limit 1 -type function forward_node87 -partition 1
set_directive_allocation -limit 1 -type function forward_node88 -partition 1
set_directive_allocation -limit 1 -type function forward_node89 -partition 1
set_directive_allocation -limit 1 -type function forward_node10 -partition 1
set_directive_allocation -limit 1 -type function forward_node11 -partition 1
set_directive_allocation -limit 1 -type function forward_node12 -partition 1
set_directive_allocation -limit 1 -type function forward_node13 -partition 1
set_directive_allocation -limit 1 -type function forward_node149 -partition 1
set_directive_allocation -limit 1 -type function forward_node150 -partition 1
set_directive_allocation -limit 1 -type function forward_node151 -partition 1
set_directive_allocation -limit 1 -type function forward_node152 -partition 1
set_directive_allocation -limit 1 -type function forward_node153 -partition 1
set_directive_allocation -limit 1 -type function forward_node154 -partition 1
set_directive_allocation -limit 1 -type function forward_node155 -partition 1
set_directive_allocation -limit 1 -type function forward_node157 -partition 1
set_directive_allocation -limit 1 -type function forward_node158 -partition 1
set_directive_allocation -limit 1 -type function forward_node159 -partition 1
set_directive_allocation -limit 1 -type function forward_node30 -partition 1
set_directive_allocation -limit 1 -type function forward_node31 -partition 1
set_directive_allocation -limit 1 -type function forward_node32 -partition 1
set_directive_allocation -limit 1 -type function forward_node33 -partition 1
set_directive_allocation -limit 1 -type function forward_node34 -partition 1
set_directive_allocation -limit 1 -type function forward_node35 -partition 1
set_directive_allocation -limit 1 -type function forward_node36 -partition 1
set_directive_allocation -limit 1 -type function forward_node160 -partition 1
set_directive_allocation -limit 1 -type function forward_node162 -partition 1
set_directive_allocation -limit 1 -type function forward_node163 -partition 1
set_directive_allocation -limit 1 -type function forward_node164 -partition 1
set_directive_allocation -limit 1 -type function forward_node165 -partition 1
set_directive_allocation -limit 1 -type function forward_node166 -partition 1
set_directive_allocation -limit 1 -type function forward_node167 -partition 1
set_directive_allocation -limit 1 -type function forward_node169 -partition 1
set_directive_allocation -limit 1 -type function forward_node0 -partition 1
set_directive_allocation -limit 1 -type function forward_node1 -partition 1
set_directive_allocation -limit 1 -type function forward_node2 -partition 1
set_directive_allocation -limit 1 -type function forward_node6 -partition 1
set_directive_allocation -limit 1 -type function forward_node7 -partition 1
set_directive_allocation -limit 1 -type function forward_node8 -partition 1
set_directive_allocation -limit 1 -type function forward_node9 -partition 1
set_directive_allocation -limit 1 -type function forward_node171 -partition 1
set_directive_allocation -limit 1 -type function forward_node170 -partition 1
set_directive_allocation -limit 1 -type function forward_node75 -partition 1
set_directive_allocation -limit 1 -type function forward_node76 -partition 1
set_directive_allocation -limit 1 -type function forward_node77 -partition 1
set_directive_allocation -limit 1 -type function forward_node78 -partition 1
set_directive_allocation -limit 1 -type function forward_node79 -partition 1

# Partition 2 functions:
set_directive_allocation -limit 1 -type function forward_node130 -partition 2
set_directive_allocation -limit 1 -type function forward_node131 -partition 2
set_directive_allocation -limit 1 -type function forward_node132 -partition 2
set_directive_allocation -limit 1 -type function forward_node133 -partition 2
set_directive_allocation -limit 1 -type function forward_node134 -partition 2
set_directive_allocation -limit 1 -type function forward_node135 -partition 2
set_directive_allocation -limit 1 -type function forward_node136 -partition 2
set_directive_allocation -limit 1 -type function forward_node137 -partition 2
set_directive_allocation -limit 1 -type function forward_node138 -partition 2
set_directive_allocation -limit 1 -type function forward_node139 -partition 2
set_directive_allocation -limit 1 -type function forward_node14 -partition 2
set_directive_allocation -limit 1 -type function forward_node15 -partition 2
set_directive_allocation -limit 1 -type function forward_node16 -partition 2
set_directive_allocation -limit 1 -type function forward_node17 -partition 2
set_directive_allocation -limit 1 -type function forward_node18 -partition 2
set_directive_allocation -limit 1 -type function forward_node19 -partition 2
set_directive_allocation -limit 1 -type function forward_node140 -partition 2
set_directive_allocation -limit 1 -type function forward_node141 -partition 2
set_directive_allocation -limit 1 -type function forward_node142 -partition 2
set_directive_allocation -limit 1 -type function forward_node143 -partition 2
set_directive_allocation -limit 1 -type function forward_node144 -partition 2
set_directive_allocation -limit 1 -type function forward_node145 -partition 2
set_directive_allocation -limit 1 -type function forward_node146 -partition 2
set_directive_allocation -limit 1 -type function forward_node147 -partition 2
set_directive_allocation -limit 1 -type function forward_node148 -partition 2
set_directive_allocation -limit 1 -type function forward_node20 -partition 2
set_directive_allocation -limit 1 -type function forward_node168 -partition 2
set_directive_allocation -limit 1 -type function forward_node59 -partition 2
set_directive_allocation -limit 1 -type function forward_node60 -partition 2
set_directive_allocation -limit 1 -type function forward_node61 -partition 2
set_directive_allocation -limit 1 -type function forward_node62 -partition 2
set_directive_allocation -limit 1 -type function forward_node63 -partition 2
set_directive_allocation -limit 1 -type function forward_node64 -partition 2
set_directive_allocation -limit 1 -type function forward_node65 -partition 2
set_directive_allocation -limit 1 -type function forward_node66 -partition 2
set_directive_allocation -limit 1 -type function forward_node67 -partition 2
set_directive_allocation -limit 1 -type function forward_node68 -partition 2
set_directive_allocation -limit 1 -type function forward_node69 -partition 2
set_directive_allocation -limit 1 -type function forward_node113 -partition 2
set_directive_allocation -limit 1 -type function forward_node114 -partition 2
set_directive_allocation -limit 1 -type function forward_node115 -partition 2
set_directive_allocation -limit 1 -type function forward_node116 -partition 2
set_directive_allocation -limit 1 -type function forward_node117 -partition 2
set_directive_allocation -limit 1 -type function forward_node118 -partition 2
set_directive_allocation -limit 1 -type function forward_node119 -partition 2
set_directive_allocation -limit 1 -type function forward_node70 -partition 2
set_directive_allocation -limit 1 -type function forward_node71 -partition 2
set_directive_allocation -limit 1 -type function forward_node72 -partition 2
set_directive_allocation -limit 1 -type function forward_node73 -partition 2
set_directive_allocation -limit 1 -type function forward_node74 -partition 2
set_directive_allocation -limit 1 -type function main -partition 2
set_directive_allocation -limit 1 -type function forward_node120 -partition 2
set_directive_allocation -limit 1 -type function forward_node121 -partition 2
set_directive_allocation -limit 1 -type function forward_node122 -partition 2
set_directive_allocation -limit 1 -type function forward_node123 -partition 2
set_directive_allocation -limit 1 -type function forward_node124 -partition 2
set_directive_allocation -limit 1 -type function forward_node125 -partition 2
set_directive_allocation -limit 1 -type function forward_node126 -partition 2
set_directive_allocation -limit 1 -type function forward_node127 -partition 2
set_directive_allocation -limit 1 -type function forward_node128 -partition 2
set_directive_allocation -limit 1 -type function forward_node129 -partition 2

# Partition 3 functions:
set_directive_allocation -limit 1 -type function forward_node92 -partition 3
set_directive_allocation -limit 1 -type function forward_node93 -partition 3
set_directive_allocation -limit 1 -type function forward_node94 -partition 3
set_directive_allocation -limit 1 -type function forward_node95 -partition 3
set_directive_allocation -limit 1 -type function forward_node96 -partition 3
set_directive_allocation -limit 1 -type function forward_node91 -partition 3
set_directive_allocation -limit 1 -type function forward_node98 -partition 3
set_directive_allocation -limit 1 -type function forward_node99 -partition 3
set_directive_allocation -limit 1 -type function forward_node90 -partition 3
set_directive_allocation -limit 1 -type function forward_node97 -partition 3
set_directive_allocation -limit 1 -type function forward_node21 -partition 3
set_directive_allocation -limit 1 -type function forward_node22 -partition 3
set_directive_allocation -limit 1 -type function forward_node23 -partition 3
set_directive_allocation -limit 1 -type function forward_node24 -partition 3
set_directive_allocation -limit 1 -type function forward_node25 -partition 3
set_directive_allocation -limit 1 -type function forward_node26 -partition 3
set_directive_allocation -limit 1 -type function forward_node27 -partition 3
set_directive_allocation -limit 1 -type function forward_node28 -partition 3
set_directive_allocation -limit 1 -type function forward_node29 -partition 3
set_directive_allocation -limit 1 -type function forward_node37 -partition 3
set_directive_allocation -limit 1 -type function forward_node38 -partition 3
set_directive_allocation -limit 1 -type function forward_node39 -partition 3
set_directive_allocation -limit 1 -type function forward_node40 -partition 3
set_directive_allocation -limit 1 -type function forward_node41 -partition 3
set_directive_allocation -limit 1 -type function forward_node42 -partition 3
set_directive_allocation -limit 1 -type function forward_node43 -partition 3
set_directive_allocation -limit 1 -type function forward_node44 -partition 3
set_directive_allocation -limit 1 -type function forward_node45 -partition 3
set_directive_allocation -limit 1 -type function forward_node46 -partition 3
set_directive_allocation -limit 1 -type function forward_node47 -partition 3
set_directive_allocation -limit 1 -type function forward_node48 -partition 3
set_directive_allocation -limit 1 -type function forward_node49 -partition 3
set_directive_allocation -limit 1 -type function forward_node3 -partition 3
set_directive_allocation -limit 1 -type function forward_node4 -partition 3
set_directive_allocation -limit 1 -type function forward_node5 -partition 3
set_directive_allocation -limit 1 -type function forward_node50 -partition 3
set_directive_allocation -limit 1 -type function forward_node51 -partition 3
set_directive_allocation -limit 1 -type function forward_node52 -partition 3
set_directive_allocation -limit 1 -type function forward_node53 -partition 3
set_directive_allocation -limit 1 -type function forward_node54 -partition 3
set_directive_allocation -limit 1 -type function forward_node55 -partition 3
set_directive_allocation -limit 1 -type function forward_node56 -partition 3
set_directive_allocation -limit 1 -type function forward_node57 -partition 3
set_directive_allocation -limit 1 -type function forward_node58 -partition 3
set_directive_allocation -limit 1 -type function forward_node100 -partition 3
set_directive_allocation -limit 1 -type function forward_node101 -partition 3
set_directive_allocation -limit 1 -type function forward_node102 -partition 3
set_directive_allocation -limit 1 -type function forward_node103 -partition 3
set_directive_allocation -limit 1 -type function forward_node104 -partition 3
set_directive_allocation -limit 1 -type function forward_node105 -partition 3
set_directive_allocation -limit 1 -type function forward_node106 -partition 3
set_directive_allocation -limit 1 -type function forward_node107 -partition 3
set_directive_allocation -limit 1 -type function forward_node108 -partition 3
set_directive_allocation -limit 1 -type function forward_node109 -partition 3
set_directive_allocation -limit 1 -type function forward_node110 -partition 3
set_directive_allocation -limit 1 -type function forward_node111 -partition 3
set_directive_allocation -limit 1 -type function forward_node112 -partition 3

# Resource utilization per partition:
# Partition 0: LUT=0, FF=0, DSP=280, BRAM=28, URAM=0
# Partition 1: LUT=0, FF=0, DSP=184, BRAM=79, URAM=0
# Partition 2: LUT=100, FF=100, DSP=215, BRAM=82, URAM=0
# Partition 3: LUT=0, FF=0, DSP=172, BRAM=79, URAM=0
