# ============================================================================
# Vivado Script: OOC Synthesis + Implementation (No Bitstream)
# For ResNet18 4x2 Partitioned Design on xcvu37p (U280-class)
# Assumes HLS RTL is exported to ./resnet18_rtl_1 by Vitis HLS
# ============================================================================

puts "=== Creating Vivado Project (ResNet18 4x2, OOC) ==="

# Create Vivado project
create_project resnet18_4_2_vivado_4 ./resnet18_4_2_vivado_project_4 -part xcvu37p-fsvh2892-2L-e -force

# Set project properties
set_property target_language Verilog [current_project]
set_property simulator_language Mixed [current_project]

# Import HLS-generated RTL
puts "Importing HLS-generated RTL..."
set hls_ip_dir "./resnet18_rtl_1"

if {![file isdirectory $hls_ip_dir]} {
    puts "WARNING: HLS RTL directory not found at $hls_ip_dir"
} else {
    # Collect RTL files from typical HLS IP layout
    set rtl_files [list]

    # Root level
    lappend rtl_files {*}[glob -nocomplain $hls_ip_dir/*.v]
    lappend rtl_files {*}[glob -nocomplain $hls_ip_dir/*.sv]
    lappend rtl_files {*}[glob -nocomplain $hls_ip_dir/*.vhd]
    lappend rtl_files {*}[glob -nocomplain $hls_ip_dir/*.vhdl]

    # hdl root
    lappend rtl_files {*}[glob -nocomplain $hls_ip_dir/hdl/*.v]
    lappend rtl_files {*}[glob -nocomplain $hls_ip_dir/hdl/*.sv]
    lappend rtl_files {*}[glob -nocomplain $hls_ip_dir/hdl/*.vhd]
    lappend rtl_files {*}[glob -nocomplain $hls_ip_dir/hdl/*.vhdl]

    # hdl/verilog + hdl/vhdl
    lappend rtl_files {*}[glob -nocomplain $hls_ip_dir/hdl/verilog/*.v]
    lappend rtl_files {*}[glob -nocomplain $hls_ip_dir/hdl/verilog/*.sv]
    lappend rtl_files {*}[glob -nocomplain $hls_ip_dir/hdl/vhdl/*.vhd]
    lappend rtl_files {*}[glob -nocomplain $hls_ip_dir/hdl/vhdl/*.vhdl]

    if {[llength $rtl_files] == 0} {
        puts "WARNING: No RTL .v/.sv/.vhd/.vhdl files found under $hls_ip_dir"
    } else {
        import_files -norecurse $rtl_files
        puts "RTL files imported successfully:"
        puts "  $rtl_files"
    }
}

# Set top module (generated by HLS)
set_property top forward [current_fileset]

# ============================================================================
# STEP 3: Apply Timing Constraints
# ============================================================================

puts "=== Applying Timing Constraints ==="

set timing_xdc [open "timing_constraints.xdc" w]
puts $timing_xdc "# Timing Constraints for ResNet18 4x2 Partitioned Design"
puts $timing_xdc "create_clock -period 5.0 -name sys_clk \[get_ports ap_clk\]"
puts $timing_xdc "set_clock_uncertainty 0.2 \[get_clocks sys_clk\]"
puts $timing_xdc "set_max_delay -from \[get_clocks sys_clk\] -to \[get_clocks sys_clk\] 4.8"
puts $timing_xdc "set_property MAX_FANOUT 50 \[get_nets -hierarchical\]"
close $timing_xdc

# Add constraints to project
add_files -fileset constrs_1 timing_constraints.xdc
set_property used_in_synthesis true [get_files timing_constraints.xdc]
set_property used_in_implementation true [get_files timing_constraints.xdc]

puts "Timing constraints applied"

# ============================================================================
# STEP 4: Out-of-Context Synthesis (avoids IO overutilization)
# ============================================================================

puts "=== Running Vivado Synthesis (Out-of-Context) ==="

### CHANGED: use synth_design directly in OOC mode instead of launch_runs
update_compile_order -fileset sources_1

synth_design -top forward \
             -part xcvu37p-fsvh2892-2L-e \
             -mode out_of_context

if {![string equal [current_design] "forward"]} {
    puts "ERROR: Synthesis did not create design 'forward'"
    exit 1
}

puts "OOC synthesis completed successfully"

# Write post-synthesis checkpoint
write_checkpoint -force post_synth_4_2_ooc.dcp

# Generate synthesis reports
report_timing_summary -file synth_4_2_timing_summary.rpt
report_utilization      -file synth_4_2_utilization.rpt
report_power            -file synth_4_2_power.rpt

# ============================================================================
# STEP 5: Apply Floorplan Constraints (on synthesized OOC design)
# ============================================================================

puts "=== Applying Floorplan Constraints ==="

# Source the floorplan constraints generated by your partitioner (if any)
if {[file exists "floorplan_constraints.tcl"]} {
    source floorplan_constraints.tcl
    puts "Floorplan constraints applied from floorplan_constraints.tcl"
} else {
    puts "WARNING: floorplan_constraints.tcl not found!"
    puts "Proceeding without floorplan constraints..."
}

# Write checkpoint after floorplan
write_checkpoint -force post_floorplan_4_2_ooc.dcp

# ============================================================================
# STEP 6: Run Implementation (Place & Route) on OOC design
# ============================================================================

puts "=== Running Implementation (Place & Route, OOC) ==="

### NEW: direct opt/place/route instead of impl_1 run

opt_design   -directive Explore
place_design -directive ExtraNetDelay_high
route_design -directive AggressiveExplore

# Check that routing finished (basic sanity: no unplaced/unrouted)
set unrouted_nets  [llength [get_nets -filter {ROUTE_STATUS != ROUTED}]]
set unplaced_cells [llength [get_cells -filter {IS_PLACED == 0}]]

if {$unplaced_cells > 0 || $unrouted_nets > 0} {
    puts "WARNING: Some cells or nets are not fully placed/routed."
    puts "  Unplaced cells : $unplaced_cells"
    puts "  Unrouted nets  : $unrouted_nets"
} else {
    puts "Implementation completed successfully (OOC)."
}

# Write post-implementation checkpoint
write_checkpoint -force post_route_4_2_ooc.dcp

# ============================================================================
# STEP 7: Implementation Reports
# ============================================================================

puts "=== Generating Implementation Reports ==="

# Timing reports
report_timing_summary -file impl_4_2_timing_summary.rpt
report_timing -sort_by group -max_paths 100 -path_type summary -file impl_4_2_timing_paths.rpt
report_clock_interaction -file 4_2_clock_interaction.rpt

# Utilization reports
report_utilization                      -file impl_4_2_utilization.rpt
report_utilization -hierarchical        -file impl_4_2_utilization_hierarchical.rpt
report_utilization -pblocks             -file impl_4_2_pblock_utilization.rpt

# Power report
report_power -file impl_4_2_power.rpt

# Route status
report_route_status -file 4_2_route_status.rpt

# DRC
report_drc -file 4_2_drc.rpt

# Control sets
report_control_sets -verbose -file 4_2_control_sets.rpt

# Clock networks
report_clock_networks -file 4_2_clock_networks.rpt

# High fanout nets
report_high_fanout_nets -file 4_2_high_fanout_nets.rpt

# ============================================================================
# NOTE: In OOC mode, bitstream/XSA generation is usually not meaningful
# for a standalone module with thousands of virtual IOs, so we skip it.
# ============================================================================

puts ""
puts "====================================================================="
puts "=== OOC Implementation Flow Complete (ResNet18 4x2) ==="
puts "====================================================================="
puts "Design: ResNet18 4x2 Partitioned"
puts "Target: xcvu37p-fsvh2892-2L-e (U280-class, 3 SLR)"
puts "Clock:  5.0ns (200MHz target)"
puts ""
puts "Output Files:"
puts " - post_synth_4_2_ooc.dcp: Post-synthesis checkpoint (OOC)"
puts " - post_floorplan_4_2_ooc.dcp: Post-floorplan checkpoint"
puts " - post_route_4_2_ooc.dcp: Post-route checkpoint"
puts " - *_4_2_*.rpt: Various synthesis/implementation reports"
puts ""

# Print timing summary
puts "=== Timing Summary ==="
set wns [get_property SLACK [get_timing_paths -max_paths 1 -nworst 1]]
set tns [get_property SLACK [get_timing_paths -max_paths 1 -nworst 1 -setup]]
puts "Worst Negative Slack (WNS): $wns ns"
puts "Total Negative Slack (TNS): $tns ns"

if {$wns >= 0} {
    puts "TIMING MET: Design meets timing constraints"
} else {
    puts "TIMING VIOLATION: Design does not meet timing constraints"
}

# Print resource utilization summary
puts ""
puts "=== Resource Utilization Summary ==="
set util_report [report_utilization -return_string]
puts $util_report

# Print per-pblock utilization if pblocks exist
if {[llength [get_pblocks]] > 0} {
    puts ""
    puts "=== Per-Partition Resource Utilization ==="
    foreach pblock [get_pblocks] {
        puts "--- $pblock ---"
        set pblock_util [report_utilization -pblocks $pblock -return_string]
        puts $pblock_util
    }
}

puts ""
puts "====================================================================="
puts "Project saved. You can reopen with:"
puts "  open_project ./resnet18_4_2_vivado_project_3/resnet18_4_2_vivado_3.xpr"
puts "====================================================================="

save_project
close_project
exit
