# Vivado SLR Constraints (Generated by HIDA LayoutPartitionPass)
catch {delete_pblocks [get_pblocks]}

proc get_func_cells {funcName} {
    set pat1 "*${funcName}*_U0"
    set c [get_cells -hier -quiet -filter "NAME =~ $pat1"]
    if {[llength $c] == 0} {
        set pat2 "*${funcName}*"
        set c [get_cells -hier -quiet -filter "NAME =~ $pat2"]
    }
    set cells [list]
    foreach cell $c { lappend cells $cell }
    return [lsort -unique $cells]
}

# Partition resource summary:
# Part 0: LUT=0 DSP=108
# Part 1: LUT=0 DSP=188
# Part 2: LUT=0 DSP=199
create_pblock pblock_partition_0
resize_pblock pblock_partition_0 -add {SLR0}
set_property CONTAIN_ROUTING true [get_pblocks pblock_partition_0]
set_property SNAPPING_MODE ON   [get_pblocks pblock_partition_0]
set partition_0_cells [list]
set _cells [get_func_cells forward_node140]
if {[llength $_cells]>0} { set partition_0_cells [concat $partition_0_cells $_cells] }
set _cells [get_func_cells forward_node97]
if {[llength $_cells]>0} { set partition_0_cells [concat $partition_0_cells $_cells] }
set _cells [get_func_cells forward_node21]
if {[llength $_cells]>0} { set partition_0_cells [concat $partition_0_cells $_cells] }
set _cells [get_func_cells forward_node166]
if {[llength $_cells]>0} { set partition_0_cells [concat $partition_0_cells $_cells] }
set _cells [get_func_cells forward_node44]
if {[llength $_cells]>0} { set partition_0_cells [concat $partition_0_cells $_cells] }
set _cells [get_func_cells forward_node6]
if {[llength $_cells]>0} { set partition_0_cells [concat $partition_0_cells $_cells] }
set _cells [get_func_cells forward_node59]
if {[llength $_cells]>0} { set partition_0_cells [concat $partition_0_cells $_cells] }
set _cells [get_func_cells forward_node125]
if {[llength $_cells]>0} { set partition_0_cells [concat $partition_0_cells $_cells] }
if {[llength $partition_0_cells] > 0} {
    add_cells_to_pblock pblock_partition_0 $partition_0_cells
}

create_pblock pblock_partition_1
resize_pblock pblock_partition_1 -add {SLR1}
set_property CONTAIN_ROUTING true [get_pblocks pblock_partition_1]
set_property SNAPPING_MODE ON   [get_pblocks pblock_partition_1]
set partition_1_cells [list]
set _cells [get_func_cells forward_node133]
if {[llength $_cells]>0} { set partition_1_cells [concat $partition_1_cells $_cells] }
set _cells [get_func_cells forward_node134]
if {[llength $_cells]>0} { set partition_1_cells [concat $partition_1_cells $_cells] }
set _cells [get_func_cells forward_node135]
if {[llength $_cells]>0} { set partition_1_cells [concat $partition_1_cells $_cells] }
set _cells [get_func_cells forward_node136]
if {[llength $_cells]>0} { set partition_1_cells [concat $partition_1_cells $_cells] }
set _cells [get_func_cells forward_node137]
if {[llength $_cells]>0} { set partition_1_cells [concat $partition_1_cells $_cells] }
set _cells [get_func_cells forward_node138]
if {[llength $_cells]>0} { set partition_1_cells [concat $partition_1_cells $_cells] }
set _cells [get_func_cells forward_node139]
if {[llength $_cells]>0} { set partition_1_cells [concat $partition_1_cells $_cells] }
set _cells [get_func_cells forward_node14]
if {[llength $_cells]>0} { set partition_1_cells [concat $partition_1_cells $_cells] }
set _cells [get_func_cells forward_node15]
if {[llength $_cells]>0} { set partition_1_cells [concat $partition_1_cells $_cells] }
set _cells [get_func_cells forward_node16]
if {[llength $_cells]>0} { set partition_1_cells [concat $partition_1_cells $_cells] }
set _cells [get_func_cells forward_node17]
if {[llength $_cells]>0} { set partition_1_cells [concat $partition_1_cells $_cells] }
set _cells [get_func_cells forward_node18]
if {[llength $_cells]>0} { set partition_1_cells [concat $partition_1_cells $_cells] }
set _cells [get_func_cells forward_node19]
if {[llength $_cells]>0} { set partition_1_cells [concat $partition_1_cells $_cells] }
set _cells [get_func_cells forward_node92]
if {[llength $_cells]>0} { set partition_1_cells [concat $partition_1_cells $_cells] }
set _cells [get_func_cells forward_node93]
if {[llength $_cells]>0} { set partition_1_cells [concat $partition_1_cells $_cells] }
set _cells [get_func_cells forward_node94]
if {[llength $_cells]>0} { set partition_1_cells [concat $partition_1_cells $_cells] }
set _cells [get_func_cells forward_node95]
if {[llength $_cells]>0} { set partition_1_cells [concat $partition_1_cells $_cells] }
set _cells [get_func_cells forward_node96]
if {[llength $_cells]>0} { set partition_1_cells [concat $partition_1_cells $_cells] }
set _cells [get_func_cells forward_node91]
if {[llength $_cells]>0} { set partition_1_cells [concat $partition_1_cells $_cells] }
set _cells [get_func_cells forward_node90]
if {[llength $_cells]>0} { set partition_1_cells [concat $partition_1_cells $_cells] }
set _cells [get_func_cells forward_node20]
if {[llength $_cells]>0} { set partition_1_cells [concat $partition_1_cells $_cells] }
set _cells [get_func_cells forward_node30]
if {[llength $_cells]>0} { set partition_1_cells [concat $partition_1_cells $_cells] }
set _cells [get_func_cells forward_node31]
if {[llength $_cells]>0} { set partition_1_cells [concat $partition_1_cells $_cells] }
set _cells [get_func_cells forward_node32]
if {[llength $_cells]>0} { set partition_1_cells [concat $partition_1_cells $_cells] }
set _cells [get_func_cells forward_node33]
if {[llength $_cells]>0} { set partition_1_cells [concat $partition_1_cells $_cells] }
set _cells [get_func_cells forward_node34]
if {[llength $_cells]>0} { set partition_1_cells [concat $partition_1_cells $_cells] }
set _cells [get_func_cells forward_node35]
if {[llength $_cells]>0} { set partition_1_cells [concat $partition_1_cells $_cells] }
set _cells [get_func_cells forward_node36]
if {[llength $_cells]>0} { set partition_1_cells [concat $partition_1_cells $_cells] }
set _cells [get_func_cells forward_node37]
if {[llength $_cells]>0} { set partition_1_cells [concat $partition_1_cells $_cells] }
set _cells [get_func_cells forward_node38]
if {[llength $_cells]>0} { set partition_1_cells [concat $partition_1_cells $_cells] }
set _cells [get_func_cells forward_node39]
if {[llength $_cells]>0} { set partition_1_cells [concat $partition_1_cells $_cells] }
set _cells [get_func_cells forward_node40]
if {[llength $_cells]>0} { set partition_1_cells [concat $partition_1_cells $_cells] }
set _cells [get_func_cells forward_node41]
if {[llength $_cells]>0} { set partition_1_cells [concat $partition_1_cells $_cells] }
set _cells [get_func_cells forward_node42]
if {[llength $_cells]>0} { set partition_1_cells [concat $partition_1_cells $_cells] }
set _cells [get_func_cells forward_node43]
if {[llength $_cells]>0} { set partition_1_cells [concat $partition_1_cells $_cells] }
set _cells [get_func_cells forward_node0]
if {[llength $_cells]>0} { set partition_1_cells [concat $partition_1_cells $_cells] }
set _cells [get_func_cells forward_node1]
if {[llength $_cells]>0} { set partition_1_cells [concat $partition_1_cells $_cells] }
set _cells [get_func_cells forward_node2]
if {[llength $_cells]>0} { set partition_1_cells [concat $partition_1_cells $_cells] }
set _cells [get_func_cells forward_node52]
if {[llength $_cells]>0} { set partition_1_cells [concat $partition_1_cells $_cells] }
set _cells [get_func_cells forward_node53]
if {[llength $_cells]>0} { set partition_1_cells [concat $partition_1_cells $_cells] }
set _cells [get_func_cells forward_node54]
if {[llength $_cells]>0} { set partition_1_cells [concat $partition_1_cells $_cells] }
set _cells [get_func_cells forward_node55]
if {[llength $_cells]>0} { set partition_1_cells [concat $partition_1_cells $_cells] }
set _cells [get_func_cells forward_node56]
if {[llength $_cells]>0} { set partition_1_cells [concat $partition_1_cells $_cells] }
set _cells [get_func_cells forward_node57]
if {[llength $_cells]>0} { set partition_1_cells [concat $partition_1_cells $_cells] }
set _cells [get_func_cells forward_node58]
if {[llength $_cells]>0} { set partition_1_cells [concat $partition_1_cells $_cells] }
set _cells [get_func_cells forward_node106]
if {[llength $_cells]>0} { set partition_1_cells [concat $partition_1_cells $_cells] }
set _cells [get_func_cells forward_node107]
if {[llength $_cells]>0} { set partition_1_cells [concat $partition_1_cells $_cells] }
set _cells [get_func_cells forward_node108]
if {[llength $_cells]>0} { set partition_1_cells [concat $partition_1_cells $_cells] }
set _cells [get_func_cells forward_node109]
if {[llength $_cells]>0} { set partition_1_cells [concat $partition_1_cells $_cells] }
set _cells [get_func_cells forward_node68]
if {[llength $_cells]>0} { set partition_1_cells [concat $partition_1_cells $_cells] }
set _cells [get_func_cells forward_node69]
if {[llength $_cells]>0} { set partition_1_cells [concat $partition_1_cells $_cells] }
set _cells [get_func_cells forward_node110]
if {[llength $_cells]>0} { set partition_1_cells [concat $partition_1_cells $_cells] }
set _cells [get_func_cells forward_node111]
if {[llength $_cells]>0} { set partition_1_cells [concat $partition_1_cells $_cells] }
set _cells [get_func_cells forward_node112]
if {[llength $_cells]>0} { set partition_1_cells [concat $partition_1_cells $_cells] }
set _cells [get_func_cells forward_node70]
if {[llength $_cells]>0} { set partition_1_cells [concat $partition_1_cells $_cells] }
set _cells [get_func_cells forward_node71]
if {[llength $_cells]>0} { set partition_1_cells [concat $partition_1_cells $_cells] }
set _cells [get_func_cells forward_node72]
if {[llength $_cells]>0} { set partition_1_cells [concat $partition_1_cells $_cells] }
set _cells [get_func_cells forward_node73]
if {[llength $_cells]>0} { set partition_1_cells [concat $partition_1_cells $_cells] }
set _cells [get_func_cells forward_node74]
if {[llength $_cells]>0} { set partition_1_cells [concat $partition_1_cells $_cells] }
if {[llength $partition_1_cells] > 0} {
    add_cells_to_pblock pblock_partition_1 $partition_1_cells
}

create_pblock pblock_partition_2
resize_pblock pblock_partition_2 -add {SLR2}
set_property CONTAIN_ROUTING true [get_pblocks pblock_partition_2]
set_property SNAPPING_MODE ON   [get_pblocks pblock_partition_2]
set partition_2_cells [list]
set _cells [get_func_cells forward_node80]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node81]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node82]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node83]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node84]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node85]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node86]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node87]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node88]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node89]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node130]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node131]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node132]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node10]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node11]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node12]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node13]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node98]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node99]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node141]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node142]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node143]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node144]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node145]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node146]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node147]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node148]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node149]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node22]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node23]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node24]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node25]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node26]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node27]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node28]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node29]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node150]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node151]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node152]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node153]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node154]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node155]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node156]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node157]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node158]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node159]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node160]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node161]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node162]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node163]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node164]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node165]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node167]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node168]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node169]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node45]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node46]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node47]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node48]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node49]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node3]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node4]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node5]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node7]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node8]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node9]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node171]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node170]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node50]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node51]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node100]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node101]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node102]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node103]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node104]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node105]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node60]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node61]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node62]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node63]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node64]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node65]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node66]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node67]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node113]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node114]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node115]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node116]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node117]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node118]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node119]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node75]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node76]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node77]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node78]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node79]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node120]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node121]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node122]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node123]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node124]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node126]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node127]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node128]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
set _cells [get_func_cells forward_node129]
if {[llength $_cells]>0} { set partition_2_cells [concat $partition_2_cells $_cells] }
if {[llength $partition_2_cells] > 0} {
    add_cells_to_pblock pblock_partition_2 $partition_2_cells
}

