# ============================================================================
# Vivado SLR Floorplan Constraints (Generated by HIDA LayoutPartitionPass)
# Target: xcvu37p (U250/U280 class)
# Partitions: 1
# NOTE: Constraints are SLR-only (no slice/DSP/BRAM subranges).
# ============================================================================

proc get_func_cells {funcName} {
    set cells [list]

    # Pattern 1: typical HLS instance, e.g. grp_forward_node82_fu_..._U0
    set pat1 "*${funcName}*_U0"
    set c [get_cells -hier -quiet -filter "NAME =~ $pat1"]

    # If nothing, try a looser pattern
    if {[llength $c] == 0} {
        set pat2 "*${funcName}*"
        set c [get_cells -hier -quiet -filter "NAME =~ $pat2"]
        puts "get_func_cells: $funcName -> [llength $c] cells (fallback pattern: $pat2)"
    } else {
        puts "get_func_cells: $funcName -> [llength $c] cells (pattern: $pat1)"
    }

    # Safely accumulate (no {*} expansion)
    foreach cell $c {
        lappend cells $cell
    }

    return [lsort -unique $cells]
}

# Partition resource summary (approximate):
#   Partition 0: LUT=100, FF=100, DSP=741, BRAM=274, URAM=0

# Remove existing pblocks to avoid conflicts.
catch {delete_pblocks [get_pblocks]}

# Create SLR-level pblocks per partition.
create_pblock pblock_partition_0
resize_pblock pblock_partition_0 -add {SLR0}
set_property CONTAIN_ROUTING true [get_pblocks pblock_partition_0]
set_property SNAPPING_MODE ON   [get_pblocks pblock_partition_0]

# Add cells for partition 0
set partition_0_cells [list]

set _cells [get_func_cells forward_node82]
if {[llength $_cells] > 0} { set partition_0_cells [concat $partition_0_cells $_cells] }

set _cells [get_func_cells forward_node85]
if {[llength $_cells] > 0} { set partition_0_cells [concat $partition_0_cells $_cells] }

set _cells [get_func_cells forward_node133]
if {[llength $_cells] > 0} { set partition_0_cells [concat $partition_0_cells $_cells] }

set _cells [get_func_cells forward_node135]
if {[llength $_cells] > 0} { set partition_0_cells [concat $partition_0_cells $_cells] }

set _cells [get_func_cells forward_node14]
if {[llength $_cells] > 0} { set partition_0_cells [concat $partition_0_cells $_cells] }

set _cells [get_func_cells forward_node16]
if {[llength $_cells] > 0} { set partition_0_cells [concat $partition_0_cells $_cells] }

set _cells [get_func_cells forward_node92]
if {[llength $_cells] > 0} { set partition_0_cells [concat $partition_0_cells $_cells] }

set _cells [get_func_cells forward_node90]
if {[llength $_cells] > 0} { set partition_0_cells [concat $partition_0_cells $_cells] }

set _cells [get_func_cells forward_node140]
if {[llength $_cells] > 0} { set partition_0_cells [concat $partition_0_cells $_cells] }

set _cells [get_func_cells forward_node97]
if {[llength $_cells] > 0} { set partition_0_cells [concat $partition_0_cells $_cells] }

set _cells [get_func_cells forward_node143]
if {[llength $_cells] > 0} { set partition_0_cells [concat $partition_0_cells $_cells] }

set _cells [get_func_cells forward_node149]
if {[llength $_cells] > 0} { set partition_0_cells [concat $partition_0_cells $_cells] }

set _cells [get_func_cells forward_node21]
if {[llength $_cells] > 0} { set partition_0_cells [concat $partition_0_cells $_cells] }

set _cells [get_func_cells forward_node24]
if {[llength $_cells] > 0} { set partition_0_cells [concat $partition_0_cells $_cells] }

set _cells [get_func_cells forward_node151]
if {[llength $_cells] > 0} { set partition_0_cells [concat $partition_0_cells $_cells] }

set _cells [get_func_cells forward_node156]
if {[llength $_cells] > 0} { set partition_0_cells [concat $partition_0_cells $_cells] }

set _cells [get_func_cells forward_node30]
if {[llength $_cells] > 0} { set partition_0_cells [concat $partition_0_cells $_cells] }

set _cells [get_func_cells forward_node32]
if {[llength $_cells] > 0} { set partition_0_cells [concat $partition_0_cells $_cells] }

set _cells [get_func_cells forward_node37]
if {[llength $_cells] > 0} { set partition_0_cells [concat $partition_0_cells $_cells] }

set _cells [get_func_cells forward_node39]
if {[llength $_cells] > 0} { set partition_0_cells [concat $partition_0_cells $_cells] }

set _cells [get_func_cells forward_node161]
if {[llength $_cells] > 0} { set partition_0_cells [concat $partition_0_cells $_cells] }

set _cells [get_func_cells forward_node166]
if {[llength $_cells] > 0} { set partition_0_cells [concat $partition_0_cells $_cells] }

set _cells [get_func_cells forward_node168]
if {[llength $_cells] > 0} { set partition_0_cells [concat $partition_0_cells $_cells] }

set _cells [get_func_cells forward_node44]
if {[llength $_cells] > 0} { set partition_0_cells [concat $partition_0_cells $_cells] }

set _cells [get_func_cells forward_node47]
if {[llength $_cells] > 0} { set partition_0_cells [concat $partition_0_cells $_cells] }

set _cells [get_func_cells forward_node0]
if {[llength $_cells] > 0} { set partition_0_cells [concat $partition_0_cells $_cells] }

set _cells [get_func_cells forward_node1]
if {[llength $_cells] > 0} { set partition_0_cells [concat $partition_0_cells $_cells] }

set _cells [get_func_cells forward_node3]
if {[llength $_cells] > 0} { set partition_0_cells [concat $partition_0_cells $_cells] }

set _cells [get_func_cells forward_node4]
if {[llength $_cells] > 0} { set partition_0_cells [concat $partition_0_cells $_cells] }

set _cells [get_func_cells forward_node6]
if {[llength $_cells] > 0} { set partition_0_cells [concat $partition_0_cells $_cells] }

set _cells [get_func_cells forward_node9]
if {[llength $_cells] > 0} { set partition_0_cells [concat $partition_0_cells $_cells] }

set _cells [get_func_cells forward_node52]
if {[llength $_cells] > 0} { set partition_0_cells [concat $partition_0_cells $_cells] }

set _cells [get_func_cells forward_node54]
if {[llength $_cells] > 0} { set partition_0_cells [concat $partition_0_cells $_cells] }

set _cells [get_func_cells forward_node59]
if {[llength $_cells] > 0} { set partition_0_cells [concat $partition_0_cells $_cells] }

set _cells [get_func_cells forward_node100]
if {[llength $_cells] > 0} { set partition_0_cells [concat $partition_0_cells $_cells] }

set _cells [get_func_cells forward_node106]
if {[llength $_cells] > 0} { set partition_0_cells [concat $partition_0_cells $_cells] }

set _cells [get_func_cells forward_node108]
if {[llength $_cells] > 0} { set partition_0_cells [concat $partition_0_cells $_cells] }

set _cells [get_func_cells forward_node62]
if {[llength $_cells] > 0} { set partition_0_cells [concat $partition_0_cells $_cells] }

set _cells [get_func_cells forward_node68]
if {[llength $_cells] > 0} { set partition_0_cells [concat $partition_0_cells $_cells] }

set _cells [get_func_cells forward_node113]
if {[llength $_cells] > 0} { set partition_0_cells [concat $partition_0_cells $_cells] }

set _cells [get_func_cells forward_node114]
if {[llength $_cells] > 0} { set partition_0_cells [concat $partition_0_cells $_cells] }

set _cells [get_func_cells forward_node119]
if {[llength $_cells] > 0} { set partition_0_cells [concat $partition_0_cells $_cells] }

set _cells [get_func_cells forward_node70]
if {[llength $_cells] > 0} { set partition_0_cells [concat $partition_0_cells $_cells] }

set _cells [get_func_cells forward_node75]
if {[llength $_cells] > 0} { set partition_0_cells [concat $partition_0_cells $_cells] }

set _cells [get_func_cells forward_node77]
if {[llength $_cells] > 0} { set partition_0_cells [concat $partition_0_cells $_cells] }

set _cells [get_func_cells main]
if {[llength $_cells] > 0} { set partition_0_cells [concat $partition_0_cells $_cells] }

set _cells [get_func_cells forward_node125]
if {[llength $_cells] > 0} { set partition_0_cells [concat $partition_0_cells $_cells] }

set _cells [get_func_cells forward_node128]
if {[llength $_cells] > 0} { set partition_0_cells [concat $partition_0_cells $_cells] }

if {[llength $partition_0_cells] > 0} {
  add_cells_to_pblock pblock_partition_0 $partition_0_cells
  puts "Added [llength $partition_0_cells] cells to pblock_partition_0"
}

puts "=== HIDA SLR floorplan constraints applied ==="
